modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="combocommands"
version="0.0.1"
displayName="ComboCommands"
displayURL="https://github.com/Ordalca/ComboCommands"
credits="Ordalca"
authors="Ordalca"
description='''
Mod adding commands related to Capture Combos.
'''

[[dependencies.modid]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.modid]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"


[[dependencies.modid]]
    modId="pixelmon"
    mandatory=true
    versionRange="[9.0.11,)"
    ordering="NONE"
    side="BOTH"